### ISSUE TITLE
no such file or directory ERROR when rake.

### ISSUE THREAD

**Issue by shunfan** [SamyPesse/tv.js#10]
Mac OS X 10.8.4

```
[load] Loading /Users/Perry/Downloads/tv.js-master/public/main/build.js ...
[build] Start building application Main
[build] Build directory : /Users/Perry/Downloads/tv.js-master/public/main/build
[build]
[html] Generating code for application
[html] End of generation
[html]
[js] Generating code for application
[js] End of generation
[js]
[stylesheet] Generating style for application
[stylesheet] End of generation
[stylesheet]
[static] Generating static files for application
[static]   -> Creating templates
[static]   -> Creating images
[static] End of generation
[static]
[load] Loading /Users/Perry/Downloads/tv.js-master/public/remote/build.js ...
[build] Start building application Remote
[build] Build directory : /Users/Perry/Downloads/tv.js-master/public/remote/build
[build]
[html] Generating code for application
[html] End of generation
[html]
[js] Generating code for application
[js] End of generation
[js]
[stylesheet] Generating style for application
[stylesheet] End of generation
[stylesheet]
[static] Generating static files for application
[static]   -> Creating templates
[static]   -> Creating images

Error: ENOENT, no such file or directory '/Users/Perry/Downloads/tv.js-master/public/remote/ressources/images'
    at Object.fs.statSync (fs.js:684:18)
    at Object.exports.copyDirSyncRecursive (/usr/local/lib/node_modules/yapp/node_modules/wrench/lib/wrench.js:179:23)
    at /usr/local/lib/node_modules/yapp/lib/builder.js:124:16
    at Function._.each._.forEach (/usr/local/lib/node_modules/yapp/node_modules/underscore/underscore.js:86:24)
    at Builder.genStatic (/usr/local/lib/node_modules/yapp/lib/builder.js:122:7)
    at Builder.build (/usr/local/lib/node_modules/yapp/lib/builder.js:59:10)
    at Application.build (/usr/local/lib/node_modules/yapp/lib/app.js:47:39)
    at Command.<anonymous> (/usr/local/lib/node_modules/yapp/bin/yapp.js:17:24)
    at Command.<anonymous> (/usr/local/lib/node_modules/yapp/node_modules/commander/index.js:254:8)
    at Command.EventEmitter.emit (events.js:98:17)
```

**Comment by idofishler** [comment]
Same here...

**Comment by AaronO** [comment]
Ok. 

That error isn't a fatal one. The server should actually be booted, simply point your servers to :

```
 http://localhost:8888/
```

And you'll get the UI served. Alternatively if you have node-webkit installed you can actually boot this as a Desktop application by running :

```
nw ./
```

Either way I'll add a message to say that the server has booted and to open your browser at the given URL.

**Comment by AaronO** [comment]
@idofishler @shunfan 

The server did boot before regardless of that error, I added a message to indicate when the server has booted and where you can connect to the web UI. (check my above comment if you desire to use node-webkit)

**Comment by shunfan** [comment]
Thanks :+1:
