### ISSUE TITLE
Error thrown shortly after clicking movie

### ISSUE THREAD

**Issue by parkerlreed** [SamyPesse/tv.js#11]
Built on an Ubuntu 13.04 machine with node 0.10.12

In terminal shortly after clicking movie (when it says buffering to 1%)

Server listening on: http://localhost:8888

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by AaronO** [comment]
It seems like you are missing `ffmpeg`.

Right now ffmpeg is required to convert movies, however issue #9 aims to fix that, making ffmpeg an optional dependency.

You'll need to install ffmpeg with `libtheora` and `libvorbis` support which are required to transcode to `OGV`.

Let me know how this works for you. And if it works provide the install command for ffmpeg, and I'll add it to the README.

**Comment by parkerlreed** [comment]
Hmm ok. I had installed ffmpeg from the repos before building. I'll see
what I can find out.

**Comment by parkerlreed** [comment]
Ok ffmpeg output concerning theora and vorbis

ffmpeg -codecs
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...S.. = Supports draw_horiz_band
 ....D. = Supports direct rendering method 1
 .....T = Supports weird frame truncation

---

 D VSD  theora          Theora
 DEA D  vorbis          Vorbis

**Comment by parkerlreed** [comment]
Compiled ffmpeg from source and made sure to have --enable-libtheora --enable-libvorbis as configure options

Same error. Is there a way to have the runtime more verbose about the error?

**Comment by marcelowa** [comment]
also experiencing the same issue
compiled it with the following ./configure
`./configure --enable-libtheora --enable-libvorbis`

**Comment by AaronO** [comment]
@parkerlreed @marcelowa 

ffmpeg's output on stderr is piped to the process' stderr so you should see it display on the command line.

I'll add some extra logging to TV.js' server side when dev mode is activated which should help.

**Comment by parkerlreed** [comment]
Everything I do to redirect stderr to a file or stdout just prints

events.js:72
        throw er; // Unhandled 'error' event
                      ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Best I can think is something messed up in the compile process. There were a bunch of things I had to manually install (npm install whaterver the build errored out on).

**Comment by idofishler** [comment]
I got the same. ffmpeg version 0.8.6-4:0.8.6-0ubuntu0.12.04.1 is installed. is there a solution for this yet?
