### ISSUE TITLE
Database not populating in OSX 10.8.4, also remote not working

### ISSUE THREAD

**Issue by ggaspari** [SamyPesse/tv.js#20]
I got it to compile and run but I'm stuck on a black screen telling me to connect my smartphone to <localhost>/remote, which also returns a "can't connect" on Chrome or Safari either in my iPhone or from the desktop.
![captura de tela 2013-07-09 as 16 55 36](https://f.cloud.github.com/assets/2135925/770801/0e6b2d8e-e8d5-11e2-9fc0-f8f6abcc173b.png)

**Comment by SamyPesse** [comment]
Use the mouse to click on the screen and you can after that use your mouse.
I'll add a message on the "intro" for this.

**Comment by SamyPesse** [comment]
On the home page, there is no movies posters until you search for somes (home page display only recent movies). Try a search (it should works).
The server runs on the port 8888 (so connect to 192.168.1.103:8888/remote/ on your smartphone). Try connecting to 192.168.1.103:8888 on your desktop, it should display the main UI and you can use your desktop mouse and keyboard for searching for movies and be sure searching works.

(Sorry for my english)

**Comment by ggaspari** [comment]
It worked OK after the instructions, really the remote port was throwing me off. But I cannot play anything, searching works and starts buffering to 1% then it throws this exception at the command line:

/Users/ggaspari/tv.js/node_modules/q/q.js:120
                    throw e;
                          ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

**Comment by AaronO** [comment]
@ggaspari Can you provide any extra information. Or is that the only stack trace you get ?

Your error is obviously some kind of network error, my guess it may be coming from the streaming part, but it's hard to tell why without any extra information.

Try with a different film or something, if you still get the same error, post your information here so I can reproduce it.

**Comment by smcavinney** [comment]
I'm having the same issue. This happens when the video gets to the 1% mark. When I press play, the video does not do anything, it just sits there. If I click back or reload, I get this error:

```
/Users/Smcavinney/tv.js-master/node_modules/q/q.js:120
                    throw e;
                             ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
make: *** [run] Error 8
```

**Comment by Floehe** [comment]
Using tv.js on OS X 10.8.4 ... when pressing play, the peerflix process starts in the background but stops downloading data after like 10 seconds. The movie never starts to play and then I will get the same error as statet in the post directly above.

When deploying the code on debian, the same torrent starts, peerflix starts downloading and I can press play after an instant, watching the movie.

Maybe something on OS X is stopping the spawned peerflix process? The process is still running but suddenly stops downloading after appr. 10 seconds.

If I can be of any help please let me know!
