### ISSUE TITLE
Error read ECONNRESET

### ISSUE THREAD

**Issue by deanchester** [SamyPesse/tv.js#30]
I keep getting this error: 

/home/pi/tv.js/node_modules/q/q.js:120
                    throw e;
                          ^
Error: read ECONNRESET
    at errnoException (net.js:878:11)
    at TCP.onread (net.js:539:19)
make: **\* [run] Error 8

It happens when i refresh a page on a remote.

**Comment by EtienneM** [comment]
Hi
I am getting the same error. I tried with Firefox and Chromium under Linux Mint 15. I get this error after starting to play a movie. The progress bar is stuck at 0% and after a while I get this error. I cannot find any log. 

Edit: To add some more information.
It actually seems that this error happened using Firefox. Using Chromium, I get no error but the progress bar is still stuck at 0%.

Some information on the softwares version I use:
- node.js: 0.10.13
- npm: 1.3.2
- ffmpeg: 0.8.6-6:0.8.6-1ubuntu2. It supports theora and vorbis.

Note that I wasn't able to connect with my phone to the website so I clicked somewhere on the screen to make the /pop-up/ asking to connect with the phone disappears.

**Comment by inglor** [comment]
I have the same error on Chromium and ubuntu build using it locally. I tried multiple movies and they end up on this error.

**Comment by emersion** [comment]
I have the same error with Chromium or Firefox.

**Comment by shaungehring** [comment]
Same issue here too.
