### ISSUE TITLE
Error: Cannot find module 'connect'

### ISSUE THREAD

**Issue by jorismulliez** [SamyPesse/tv.js#31]
Hi,

I can't launch the app, there is an error : 

```
~/tv.js/tv.js-master $ make run
/usr/bin/node bin/run.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'connect'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (~/tv.js/tv.js-master/node_modules/express/lib/express.js:5:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
make: *** [run] Error 8
```

Thanks in advance !

**Comment by AaronO** [comment]
What platform are you using ?

`connect` is not used directly by TV.js but instead directly through the `express` framework.

Try reinstalling the node dependencies, with :

```
rm -rf ./node_modules/ && npm install .
```

Either way it looks like your error isn't TV.js specific but rather with express.

**Comment by jorismulliez** [comment]
I'm on linux Mint 13.
I tried your solution, and it looks like better, but I have a new error : 

```
~/tv.js/tv.js-master $ make run
/usr/bin/node bin/run.js
Server listening on: http://localhost:8888
Error: ENOENT, stat '~/tv.js/tv.js-master/public/main/build/index.html'
```

Have you any idea ?
