### ISSUE TITLE
Freezing Up

### ISSUE THREAD

**Issue by BrysonR** [SamyPesse/tv.js#39]
It seems to be working well so far in regards to building and beginning to run it locally but every time I go to watch a movie it stops downloading after exactly 10 seconds.

**Comment by yoanvillanueva** [comment]
I have exactly the same problem

**Comment by clooket** [comment]
same problem

**Comment by sdgandhi** [comment]
exactly same problem. the download speed freezes and sometimes this is printed to the console: 

```
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

**Comment by gkze** [comment]
I can confirm this also

**Comment by sdgandhi** [comment]
I believe it is a problem with the peerflix program. I ran peerflix separately from command line (after downloading it from the peerflix repo), and it seems to run correctly however.

I think there might be some internal connection problem between tv.js and peerflix? I haven't looked too much into the internals yet, but may do so this weekend.

**Comment by Floehe** [comment]
I had the same feeling as well, that the connection with peerflix is causing the problem. When I use the command created by tv.js for the peerflix binary on the command line itself, its working. It's not working when it is called by tv.js however.
