### ISSUE TITLE
Error Streaming on Raspberry Pi

### ISSUE THREAD

**Issue by BrysonR** [SamyPesse/tv.js#41]
Error in Deferred callbacks (file: undefined line: undefined) : ReferenceError :  MediaError is not defined ReferenceError: MediaError is not defined

It says this happens at multiple different places. 

at Page.extend.updateMessages (http://localhost:8888/static/application.js:30532:63)
    at Page.extend.finish (http://localhost:8888/static/application.js:30342:18)
    at Class.extend.ready (http://localhost:8888/static/application.js:23659:18)
    at Class.extend.renderComponents (http://localhost:8888/static/application.js:23753:54)
    at null.<anonymous> (http://localhost:8888/static/application.js:23467:50)
    at Class.extend.triggerEvents (http://localhost:8888/static/application.js:13578:67)
    at Class.extend.triggerOnly (http://localhost:8888/static/application.js:13561:30)
    at null.<anonymous> (http://localhost:8888/static/application.js:13571:34)
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:8888/static/application.js:12259:11) 
ReferenceError
 application.js:22950
Class.extend._call

**Comment by d0nd3r3k** [comment]
Ran into the same error, that's why I suggest using the native omxplayer to stream the movies instead of ffmpeg.
